#!/bin/bash

DESTDIR=/tmp/FriendlyARM/mini210/kernel
mkdir -p ${DESTDIR}

# build zImage for linux
cp mini210_linux_defconfig .config && \
	make &&
	cp -vf arch/arm/boot/zImage ${DESTDIR}/zImage || exit 1

cp mini210-tvp5150_linux_defconfig .config && \
	make &&
	cp -vf arch/arm/boot/zImage ${DESTDIR}/zImage_tvp5150 || exit 1

make distclean

# build zImage for android
cp mini210_android_defconfig .config && \
	make &&
	cp -vf arch/arm/boot/zImage ${DESTDIR}/azImage || exit 1

cp mini210-tvp5150_android_defconfig .config && \
	make &&
	cp -vf arch/arm/boot/zImage ${DESTDIR}/azImage_tvp5150 || exit 1

